In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#import ydata_profiling
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import GridSearchCV
import xgboost
%matplotlib inline

In [ ]:
from google.colab import files
uploades = files.upload()

In [ ]:
df = pd.read_csv('dataset.csv')

In [ ]:
le = LabelEncoder()

# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df['Target'])
# removing the column 'Purchased' from df
# as it is of no use now.
df.drop("Target", axis=1, inplace=True)

# Appending the array to our dataFrame
# with column name 'Purchased'
df["Target"] = label

# printing Dataframe
df.tail(5)
df['Target'].unique()

array([0, 2, 1])

In [ ]:
df.head()

Marital status  Application mode  Application order  Course  \
0               1                 8                  5       2   
1               1                 6                  1      11   
2               1                 1                  5       5   
3               1                 8                  2      15   
4               2                12                  1       3   

   Daytime/evening attendance  Previous qualification  Nacionality  \
0                           1                       1            1   
1                           1                       1            1   
2                           1                       1            1   
3                           1                       1            1   
4                           0                       1            1   

   Mother's qualification  Father's qualification  Mother's occupation  ...  \
0                      13                      10                    6  ...   
1                       1                       3                    4  ...   
2                      22                      27                   10  ...   
3                      23                      27                    6  ...   
4                      22                      28                   10  ...   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    0   
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    6   
4                                    0                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP  Target  
0             1.4  1.74       0  
1            -0.3  0.79       2  
2             1.4  1.74       0  
3            -0.8 -3.12       2  
4            -0.3  0.79       2  

[5 rows x 35 columns]

In [ ]:
# data_top = df.head()
# for col in df.columns:
#   print(df[col].unique())

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
X = df.drop(['Target'],axis=1)
y = df['Target']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3 ,random_state=42)

In [ ]:
param_grid = [  {'learning_rate': [0.01,0.001,0.1,0.2,0.02], 'max_depth':range(0,10,1),
                 }]

In [ ]:
import IPython
from google.colab import output
display(IPython.display.Javascript('''
function ClickConnect()
  btn == document. querySelector("colab-connect-button")
  if (btn ! = null) {
    console. log("Click colab-connect-button");
    btn.click()
    }
  btn = document.getElementById(ok')
  if (btn != null) {
    console. .log("Click reconnect");
    btn.click()
                               I
setInterval(ClickConnect,60000)
'''))


<IPython.core.display.Javascript object>

In [ ]:
from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=10, random_state=10)
# from lightgbm import LightGBMClassifier
xgb = xgboost.XGBClassifier()
grid_search = GridSearchCV(xgb, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'learning_rate': 0.2, 'max_depth': 3}

In [ ]:
# import warnings
# warnings.filterwarnings('ignore')

In [ ]:
param_grid = [  {'learning_rate': [0.2], 'max_depth':[4],'max_leaves' : range(10,50),
                 }]
# from lightgbm import LightGBMClassifier
xgb = xgboost.XGBClassifier()
grid_search = GridSearchCV(xgb, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'learning_rate': 0.2, 'max_depth': 4, 'max_leaves': 10}

In [ ]:
param_grid = [  {'learning_rate': [0.2], 'max_depth':[4],'max_leaves' : [10],'min_child_weight':range(0,10,1),
                 }]
# from lightgbm import LightGBMClassifier
xgb = xgboost.XGBClassifier()
grid_search = GridSearchCV(xgb, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'learning_rate': 0.2, 'max_depth': 4, 'max_leaves': 10, 'min_child_weight': 2}

In [ ]:
param_grid = [  {'learning_rate': [0.2], 'max_depth':[4],'max_leaves' : [10],'min_child_weight':[2],'subsample':[0.8,0.9,1],
                 }]
# from lightgbm import LightGBMClassifier
xgb = xgboost.XGBClassifier()
grid_search = GridSearchCV(xgb, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'learning_rate': 0.2,
 'max_depth': 4,
 'max_leaves': 10,
 'min_child_weight': 2,
 'subsample': 1}

In [ ]:
param_grid = [  {'learning_rate': [0.2], 'max_depth':[4],'max_leaves' : [10],'min_child_weight':[2],'subsample':[1],
                 'colsample_bytree':[0.8,0.9,1],'gamma':[0,0.01,0.02],
                 }]
# from lightgbm import LightGBMClassifier
xgb = xgboost.XGBClassifier()
grid_search = GridSearchCV(xgb, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'colsample_bytree': 0.8,
 'gamma': 0.01,
 'learning_rate': 0.2,
 'max_depth': 4,
 'max_leaves': 10,
 'min_child_weight': 2,
 'subsample': 1}

In [ ]:
grid_search.best_score_

0.7794893428526761

In [ ]:
best_xgb = grid_search.best_estimator_

In [ ]:
best_xgb.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=0.01, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.2, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=10,
              min_child_weight=2, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [ ]:
pred_y = best_xgb.predict(X_test)

In [ ]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import accuracy_score, precision_score, classification_report,f1_score, recall_score, confusion_matrix
accuracy = accuracy_score(y_test, pred_y)
print(accuracy)
recall = recall_score(y_test, pred_y,average='macro')
print(recall)
precision = precision_score(y_test, pred_y,average='macro')
print(precision)
f1 = f1_score(y_test, pred_y,average='macro')
print(f1)
print('Classification report for XGB Model:\n',classification_report(y_test, pred_y))

0.7725903614457831
0.6944115964142666
0.7251570063514131
0.7029485076039629
Classification report for XGB Model:
               precision    recall  f1-score   support

           0       0.81      0.78      0.79       441
           1       0.57      0.39      0.46       245
           2       0.80      0.92      0.85       642

    accuracy                           0.77      1328
   macro avg       0.73      0.69      0.70      1328
weighted avg       0.76      0.77      0.76      1328



In [ ]:
print(confusion_matrix(y_test, pred_y))

[[342  44  55]
 [ 56  96  93]
 [ 25  29 588]]


In [ ]:
# grid_search = GridSearchCV(xgb, param_grid, cv = 5, return_train_score = True, n_jobs = -1)

In [ ]:
# grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=XGBClassifier(), n_jobs=-1,
             param_grid=[{'colsample_bytree': [0.4, 0.5, 0.7],
                          'gamma': [0.0, 0.1, 0.2],
                          'learning_rate': [0.2, 0.3, 0.4],
                          'max_depth': [5, 6, 7],
                          'min_child_weight': [0, 1, 2, 3]}],
             return_train_score=True)

In [ ]:
# grid_search.cv_results_

{'mean_fit_time': array([1.41639228, 1.38559093, 0.96245122, 0.93454881, 1.20030146,
        1.53229012, 1.18627753, 1.12951522, 1.58957815, 1.90805469,
        1.36075511, 1.33411865, 1.41658893, 0.95781641, 0.95848041,
        0.93043842, 1.66171045, 1.14304519, 1.25001578, 1.62059059,
        1.75798073, 1.38165693, 1.5052299 , 1.5842452 , 1.07295032,
        0.94889755, 1.0872963 , 1.24520731, 1.21979856, 1.14204946,
        1.34285727, 1.31728325, 1.48973579, 1.34714437, 1.76309681,
        1.33236847, 0.98926058, 1.19095421, 1.1968071 , 0.95232787,
        1.1994348 , 1.39915266, 1.33065038, 1.12843981, 1.5346252 ,
        1.79433899, 1.35053821, 1.33980784, 1.33878489, 1.01697416,
        0.93881121, 0.93328414, 1.47639623, 1.3538281 , 1.14469461,
        1.12101498, 1.95457864, 1.35652642, 1.3421659 , 1.7667788 ,
        0.98235922, 0.96372247, 0.95411172, 1.05573802, 1.51259665,
        1.16931477, 1.13756776, 1.53216271, 1.49291787, 1.33499808,
        1.64818501, 1.46681271,

In [ ]:
# grid_search.best_estimator_

XGBClassifier(colsample_bytree=0.7, gamma=0.2, learning_rate=0.2, max_depth=5,
              objective='multi:softprob')

In [ ]:
# grid_search.best_score_
# #cross validation training score

0.7880756598662286

In [ ]:
# best_xgb = grid_search.best_estimator_

In [ ]:
# best_xgb.fit(X_train,y_train)

XGBClassifier(colsample_bytree=0.7, gamma=0.2, learning_rate=0.2, max_depth=5,
              objective='multi:softprob')

In [ ]:
# import pickle
# filename = 'finalized_model_XGB.sav'
# pickle.dump(best_xgb, open(filename, 'wb'))

In [ ]:
# pred_y = best_xgb.predict(X_test)

In [ ]:
# from sklearn.metrics import accuracy_score
# accuracy = accuracy_score(y_test,pred_y)

In [ ]:
# accuracy
# #test_accuracy

0.7593220338983051