In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#import ydata_profiling
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import GridSearchCV
import lightgbm
%matplotlib inline

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import files
uploades = files.upload()

Saving obesity_preprocessed.csv to obesity_preprocessed.csv


In [ ]:
df = pd.read_csv('obesity_preprocessed.csv')

In [ ]:
df.head()

Age  Height  Weight  FCVC  NCP  CH2O  FAF  TUE  Target  Gender_Female  \
0  21.0    1.62    64.0   2.0  3.0   2.0  0.0  1.0       1              1   
1  21.0    1.52    56.0   3.0  3.0   3.0  3.0  0.0       1              1   
2  23.0    1.80    77.0   2.0  3.0   2.0  2.0  1.0       1              0   
3  27.0    1.80    87.0   3.0  3.0   2.0  2.0  0.0       5              0   
4  22.0    1.78    89.8   2.0  1.0   2.0  0.0  0.0       6              0   

   ...  SCC_yes  CALC_Always  CALC_Frequently  CALC_Sometimes  CALC_no  \
0  ...        0            0                0               0        1   
1  ...        1            0                0               1        0   
2  ...        0            0                1               0        0   
3  ...        0            0                1               0        0   
4  ...        0            0                0               1        0   

   MTRANS_Automobile  MTRANS_Bike  MTRANS_Motorbike  \
0                  0            0                 0   
1                  0            0                 0   
2                  0            0                 0   
3                  0            0                 0   
4                  0            0                 0   

   MTRANS_Public_Transportation  MTRANS_Walking  
0                             1               0  
1                             1               0  
2                             1               0  
3                             0               1  
4                             1               0  

[5 rows x 32 columns]

In [ ]:
X = df.drop(['Target'],axis=1)
y = df['Target']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3 ,random_state=42)

In [ ]:
param_grid = [  {'learning_rate': [0.01,0.001,0.1,0.2,0.02], 'max_depth':range(4,10,1),
                 }]

In [ ]:
from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=10, random_state=10)

In [ ]:
# from lightgbm import LightGBMClassifier
lgm = lightgbm.LGBMClassifier()
grid_search = GridSearchCV(lgm, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
import IPython
from google.colab import output
display(IPython.display.Javascript('''
function ClickConnect()
  btn == document. querySelector("colab-connect-button")
  if (btn ! = null) {
    console. log("Click colab-connect-button");
    btn.click()
    }
  btn = document.getElementById(ok')
  if (btn != null) {
    console. .log("Click reconnect");
    btn.click()
                               I
setInterval(ClickConnect,60000)
'''))


<IPython.core.display.Javascript object>

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'learning_rate': 0.1, 'max_depth': 9}

In [ ]:
param_grid = [  {'learning_rate': [0.1], 'max_depth':[9],'num_iterations' : range(80,150,10),
                 }]

# from lightgbm import LightGBMClassifier
lgm = lightgbm.LGBMClassifier()
grid_search = GridSearchCV(lgm, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'learning_rate': 0.1, 'max_depth': 9, 'num_iterations': 130}

In [ ]:
param_grid = [  {'learning_rate': [0.1], 'max_depth':[9],'num_iterations' : [130],
                 'num_leaves': range(20,40,1),
                 }]

# from lightgbm import LightGBMClassifier
lgm = lightgbm.LGBMClassifier()
grid_search = GridSearchCV(lgm, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'learning_rate': 0.1, 'max_depth': 9, 'num_iterations': 130, 'num_leaves': 31}

In [ ]:
param_grid = [  {'learning_rate': [0.1], 'max_depth':[9],'num_iterations' : [130],
                 'num_leaves': [31], 'min_data_in_leaf': range(10,20,1),
                 }]

# from lightgbm import LightGBMClassifier
lgm = lightgbm.LGBMClassifier()
grid_search = GridSearchCV(lgm, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'learning_rate': 0.1,
 'max_depth': 9,
 'min_data_in_leaf': 17,
 'num_iterations': 130,
 'num_leaves': 31}

In [ ]:
param_grid = [  {'learning_rate': [0.1], 'max_depth':[9],'num_iterations' : [130],
                 'num_leaves': [31], 'min_data_in_leaf': [17],'max_bin':range(10,50,10),'feature_fraction':[0.8,0.9,1],
 'bagging_fraction':[0.8,0.9,1],
                 }]

# from lightgbm import LightGBMClassifier
lgm = lightgbm.LGBMClassifier()
grid_search = GridSearchCV(lgm, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'bagging_fraction': 0.8,
 'feature_fraction': 0.9,
 'learning_rate': 0.1,
 'max_bin': 40,
 'max_depth': 9,
 'min_data_in_leaf': 17,
 'num_iterations': 130,
 'num_leaves': 31}

In [ ]:
param_grid = [  {'learning_rate': [0.1], 'max_depth':[9],'num_iterations' : [130],
                 'num_leaves': [31], 'min_data_in_leaf': [17],'max_bin':[40],'feature_fraction':[0.9],
 'bagging_fraction':[0.8],'lambda_l1':[0,0.1,0.2],'lambda_l2':[0,0.1,0.2], 'min-gain_to_split':[0,0.1,0.2],
                 }]

# from lightgbm import LightGBMClassifier
lgm = lightgbm.LGBMClassifier()
grid_search = GridSearchCV(lgm, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'bagging_fraction': 0.8,
 'feature_fraction': 0.9,
 'lambda_l1': 0,
 'lambda_l2': 0,
 'learning_rate': 0.1,
 'max_bin': 40,
 'max_depth': 9,
 'min-gain_to_split': 0,
 'min_data_in_leaf': 17,
 'num_iterations': 130,
 'num_leaves': 31}

In [ ]:
grid_search.best_score_

0.9723096655978012

In [ ]:
best_lgbm = grid_search.best_estimator_

In [ ]:
best_lgbm.fit(X_train,y_train)

LGBMClassifier(bagging_fraction=0.8, feature_fraction=0.9, lambda_l1=0,
               lambda_l2=0, max_bin=40, max_depth=9, min-gain_to_split=0,
               min_data_in_leaf=17, num_iterations=130)

In [ ]:
pred_y = best_lgbm.predict(X_test)

In [ ]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import accuracy_score, precision_score, classification_report,f1_score, recall_score, confusion_matrix
accuracy = accuracy_score(y_test, pred_y)
print(accuracy)
recall = recall_score(y_test, pred_y,average='macro')
print(recall)
precision = precision_score(y_test, pred_y,average='macro')
print(precision)
f1 = f1_score(y_test, pred_y,average='macro')
print(f1)
print('Classification report for LIGHTGBM Model:\n',classification_report(y_test, pred_y))

0.9668769716088328
0.9668708750450158
0.9672820027202433
0.9670431417593945
Classification report for LIGHTGBM Model:
               precision    recall  f1-score   support

           0       0.97      0.98      0.97        86
           1       0.91      0.92      0.91        93
           2       0.98      0.98      0.98       102
           3       0.98      0.98      0.98        88
           4       1.00      0.99      0.99        98
           5       0.94      0.93      0.94        88
           6       1.00      0.99      0.99        79

    accuracy                           0.97       634
   macro avg       0.97      0.97      0.97       634
weighted avg       0.97      0.97      0.97       634



In [ ]:
print(confusion_matrix(y_test, pred_y))

[[ 84   2   0   0   0   0   0]
 [  3  86   0   0   0   4   0]
 [  0   0 100   1   0   1   0]
 [  0   0   2  86   0   0   0]
 [  0   0   0   1  97   0   0]
 [  0   6   0   0   0  82   0]
 [  0   1   0   0   0   0  78]]
