In [ ]:
#!pip install pandas-profiling
#!pip3 install -U matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#import ydata_profiling
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline


In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import files
uploades = files.upload()

Saving ObesityDataSet_raw_and_data_sinthetic.csv to ObesityDataSet_raw_and_data_sinthetic.csv


In [ ]:
df = pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv',header=0)
df.head()

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no   2.0   
1  Female  21.0    1.52    56.0                            yes   no   3.0   
2    Male  23.0    1.80    77.0                            yes   no   2.0   
3    Male  27.0    1.80    87.0                             no   no   3.0   
4    Male  22.0    1.78    89.8                             no   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II

In [ ]:
df.shape

(2111, 17)

In [ ]:
df = df.rename(columns={'NObeyesdad': 'Target'})

In [ ]:
df.head()

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no   2.0   
1  Female  21.0    1.52    56.0                            yes   no   3.0   
2    Male  23.0    1.80    77.0                            yes   no   2.0   
3    Male  27.0    1.80    87.0                             no   no   3.0   
4    Male  22.0    1.78    89.8                             no   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   

                  MTRANS               Target  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II

In [ ]:
df['Target'].value_counts()

Obesity_Type_I         351
Obesity_Type_III       324
Obesity_Type_II        297
Overweight_Level_I     290
Overweight_Level_II    290
Normal_Weight          287
Insufficient_Weight    272
Name: Target, dtype: int64

In [ ]:
df.dtypes

Gender                             object
Age                               float64
Height                            float64
Weight                            float64
family_history_with_overweight     object
FAVC                               object
FCVC                              float64
NCP                               float64
CAEC                               object
SMOKE                              object
CH2O                              float64
SCC                                object
FAF                               float64
TUE                               float64
CALC                               object
MTRANS                             object
Target                             object
dtype: object

In [ ]:
nominal = ['Gender','family_history_with_overweight', 'FAVC','CAEC','SMOKE','SCC','CALC','MTRANS']
for i in nominal:
        df = pd.concat([df,pd.get_dummies(df[i], prefix=i)],axis=1)
        df.drop([i],axis=1, inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# Encode labels in column 'species'.
df['Target']= label_encoder.fit_transform(df['Target'])

df['Target'].unique()

array([1, 5, 6, 2, 0, 3, 4])

In [ ]:
df.head()

Age  Height  Weight  FCVC  NCP  CH2O  FAF  TUE  Target  Gender_Female  \
0  21.0    1.62    64.0   2.0  3.0   2.0  0.0  1.0       1              1   
1  21.0    1.52    56.0   3.0  3.0   3.0  3.0  0.0       1              1   
2  23.0    1.80    77.0   2.0  3.0   2.0  2.0  1.0       1              0   
3  27.0    1.80    87.0   3.0  3.0   2.0  2.0  0.0       5              0   
4  22.0    1.78    89.8   2.0  1.0   2.0  0.0  0.0       6              0   

   ...  SCC_yes  CALC_Always  CALC_Frequently  CALC_Sometimes  CALC_no  \
0  ...        0            0                0               0        1   
1  ...        1            0                0               1        0   
2  ...        0            0                1               0        0   
3  ...        0            0                1               0        0   
4  ...        0            0                0               1        0   

   MTRANS_Automobile  MTRANS_Bike  MTRANS_Motorbike  \
0                  0            0                 0   
1                  0            0                 0   
2                  0            0                 0   
3                  0            0                 0   
4                  0            0                 0   

   MTRANS_Public_Transportation  MTRANS_Walking  
0                             1               0  
1                             1               0  
2                             1               0  
3                             0               1  
4                             1               0  

[5 rows x 32 columns]

In [ ]:
df.to_csv('obesity_preprocessed.csv', encoding='utf-8', index=False)

In [ ]:
X = df.drop(['Target'],axis=1)
y = df['Target']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3 ,random_state=42)

In [ ]:
from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=10, random_state=10)

In [ ]:
param_grid = [{'n_estimators': range(50, 150, 10), 'max_depth' : range(1,10,1), }]
rf = RandomForestClassifier()
grid_search = GridSearchCV(rf, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_estimator_

RandomForestClassifier(max_depth=9, n_estimators=130)

In [ ]:
grid_search.best_params_

{'max_depth': 9, 'n_estimators': 130}

In [ ]:
param_grid = [{'n_estimators': [130], 'max_depth' : [9],
               'min_samples_leaf' : range(1,10,1),
               'min_samples_split': range(2,10,1),}]
rf = RandomForestClassifier()
grid_search = GridSearchCV(rf, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_estimator_

RandomForestClassifier(max_depth=9, n_estimators=130)

In [ ]:
grid_search.best_params_

{'max_depth': 9,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 130}

In [ ]:
param_grid = [{'n_estimators': [130], 'max_depth' : [9],
               'min_samples_leaf' : [1],
               'min_samples_split': [2],
               'max_features': ['sqrt','log2','None'],'bootstrap': [True,False]
               }]
rf = RandomForestClassifier()
grid_search = GridSearchCV(rf, param_grid, cv=cv, return_train_score=True, n_jobs = -1)

In [ ]:
grid_search.fit(X_train, y_train)
grid_search.best_params_

{'bootstrap': False,
 'max_depth': 9,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 130}

In [ ]:
grid_search.best_score_

0.9292546953733393

In [ ]:
best_rf = grid_search.best_estimator_

In [ ]:
best_rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=False, max_depth=9, n_estimators=130)

In [ ]:
pred_y = best_rf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, classification_report,f1_score, recall_score, confusion_matrix
accuracy = accuracy_score(y_test, pred_y)
print(accuracy)
recall = recall_score(y_test, pred_y,average='macro')
print(recall)
precision = precision_score(y_test, pred_y,average='macro')
print(precision)
f1 = f1_score(y_test, pred_y,average='macro')
print(f1)
print('Classification report for Random forest Model:\n',classification_report(y_test, pred_y))

0.919558359621451
0.9189154060958723
0.9220276151231589
0.9191164615392304
Classification report for Random forest Model:
               precision    recall  f1-score   support

           0       0.95      0.93      0.94        86
           1       0.77      0.89      0.83        93
           2       0.98      0.91      0.94       102
           3       0.97      0.99      0.98        88
           4       1.00      0.99      0.99        98
           5       0.90      0.80      0.84        88
           6       0.89      0.92      0.91        79

    accuracy                           0.92       634
   macro avg       0.92      0.92      0.92       634
weighted avg       0.92      0.92      0.92       634



In [ ]:
print(confusion_matrix(y_test, pred_y))

[[80  6  0  0  0  0  0]
 [ 4 83  0  0  0  4  2]
 [ 0  3 93  3  0  1  2]
 [ 0  0  1 87  0  0  0]
 [ 0  0  1  0 97  0  0]
 [ 0 13  0  0  0 70  5]
 [ 0  3  0  0  0  3 73]]
